version: '3'

services:

    camunda-postgres:
        # restart: always
        build:
            context: .
            dockerfile: camunda/Dockerfile
        image: tnex/camunda-bpm-platform:0.1.0
        environment:
            - DB_DRIVER=org.postgresql.Driver
            - DB_URL=jdbc:postgresql://postgres:5432/camunda
            - DB_USERNAME=camunda
            - DB_PASSWORD=camunda
            - WAIT_FOR=postgres:5432
        links:
            - postgres
        ports:
            - "8080:8080"
        restart: unless-stopped
        volumes:
            - ./camunda:/build


    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=camunda
            - POSTGRES_PASSWORD=camunda
        ports:
            - "5432:5432"